services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
  wallopenings-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallopenings
    ports:
      - 5400:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  wallopenings-redis:
    image: redis:7-alpine
    container_name: wallopenings-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: