services:
  server:
    container_name: wall-openings-be
    image: ${ECR_REGISTRY}/wall-openings-be:${GIT_SHA}
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    ports:
      - 127.0.0.1:5000:5000
    networks:
      - web
      - default
    depends_on:
      - wallopenings-db
      - redis
    restart: unless-stopped

  wallopenings-db:
    container_name: wall-openings-db
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5400:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

networks:
  web:
    external: true

volumes:
  postgres_data:
  redis_data:
